### ISSUE TITLE
Installation/Usage instructions?

### ISSUE THREAD

**Issue by BaseInfinity** [ScrapeWithYuri/Live-Sports-Arbitrage-Bet-Finder#1]
Would it be possible to add installation and usage instructions? 

I understand one needs to install the Chromedriver and selenium, but it's still not clear on how to run these scripts

**Comment by BaseInfinity** [comment]
Thanks for your hard work, this tool looks awesome

**Comment by personal-coding** [comment]
The programs are written in Python, so you can run them via command line or other Python IDEs. You'll need these libraries:

1. selenium
2. numpy
3. nashpy
4. tkinter
5. undetected-chromedriver-modified
6. gevent

The undetected-chromedriver-modified library will automatically detect the proper ChromeDriver version that you need, and will install it for you. Once you've downloaded the libraries, the scripts should run by opening a Chrome browser and a tkinter window. The tkinter window will have a start and stop button.

**Comment by BaseInfinity** [comment]
Thanks for the instructions! Ill try it out and get back to you when I have more free time, thanks again
