### ISSUE TITLE
anyway to get around this warning? "... page has been denied because we believe you are using automation tools..."

### ISSUE THREAD

**Issue by cpbarry80** [ScrapeWithYuri/Live-Sports-Arbitrage-Bet-Finder#12]
anyway to get around this warning? "... page has been denied because we believe you are using automation tools..."

below is the message: 

> Access to this page has been denied because we believe you are using automation tools to browse the website.
> 
> This may happen as a result of the following:
> 
> Javascript is disabled or blocked by an extension (ad blockers for example)
> Your browser does not support cookies
> 
> Please make sure that Javascript and cookies are enabled on your browser and that you are not blocking them from loading.
> 
> Using ad blocker (e.g. uBlock Origin, AdBlock, Adblock Plus, etc.)?
> 
> Please disable your ad blocker temporarily

**Comment by browneandrae** [comment]
This seems like you need to need a rotating proxy like zyte as their
program is blocking your tools. Been pretty busy haven't had a chance to
take a look.

**Comment by personal-coding** [comment]
@cpbarry80 The program utilizes the [undetected-chromedriver](https://pypi.org/project/undetected-chromedriver/) package to help avoid bot detection. However, bot detection techniques change frequently, so the package may be identified as a bot from time-to-time.

The package notes that it does not hide IP addresses. Depending on your IP reputation, bot detection may not pass.

You can try utilizing the undetected-chromedriver-modified package as well.
