### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Pabloet12** [ScrapeWithYuri/Live-Sports-Arbitrage-Bet-Finder#13]
Hello,

I have installed all the specified libraries and when I run the code, I get this error
![image](https://github.com/personal-coding/Live-Sports-Arbitrage-Bet-Finder/assets/156537923/388c5719-8750-4a21-97ec-5a006ad2c602)
As you can see, since I am using the library : undetected-chromedriver-modified, I have modified the code to:  import undetected_chromedriver.v2 as uc

![image](https://github.com/personal-coding/Live-Sports-Arbitrage-Bet-Finder/assets/156537923/07f0e38e-40c6-46af-bbdc-cee468f71792)

Any ideas how to solve that?

Thanks in advance.

**Comment by personal-coding** [comment]
@Pabloet12 The below answer on Stackoverflow should resolve that issue. However, I would not recommend using the `-modified` version of the undetected chromedriver library. You can use undetected-chromedriver and remove `.v2` from the library import.

https://stackoverflow.com/questions/69381312/importerror-cannot-import-name-from-collections-using-python-3-10
