### ISSUE TITLE
X Path Selector unable to find element

### ISSUE THREAD

**Issue by nealmick** [ScrapeWithYuri/Live-Sports-Arbitrage-Bet-Finder#14]
Some of the xpath selectors appear to be in need of update.  Specifically the bet slip selector or case 3 and 4 of the processing function in FD 2 Player appears to be referencing stale element.    any insight is greatly appreciated.  

LINE 173 ""//div[contains(@class,'betslip-odds__display-standard')]/span").text.strip()"): Message: stale element reference: stale element not found

**Comment by personal-coding** [comment]
@nealmick I am not actively maintaining this repository, as websites frequently change. I provided the code for informational purposes. Here is a helpful reference to update the XPath selectors:

https://www.browserstack.com/guide/xpath-in-selenium
