### ISSUE TITLE
No module named gevent

### ISSUE THREAD

**Issue by Terio1** [ScrapeWithYuri/Live-Sports-Arbitrage-Bet-Finder#15]
Traceback (most recent call last):
  File "C:\Users\porte\Downloads\Live-Sports-Arbitrage-Bet-Finder-main\Live-Sports-Arbitrage-Bet-Finder-main\F & W - Arb_Website - Two Person.py", line 1, in <module>
    from gevent.pool import Pool
ModuleNotFoundError: No module named 'gevent'

Anyway to get around this thanks in advance

**Comment by Terio1** [comment]
ended up fixing it could you update the xpaths for ceaser instead of william hill

**Comment by personal-coding** [comment]
@Terio1 I am not actively maintaining this repository, as websites frequently change. I provided the code for informational purposes. Here is a helpful reference to update the XPath selectors:

https://www.browserstack.com/guide/xpath-in-selenium
