### ISSUE TITLE
Driver Error

### ISSUE THREAD

**Issue by caderob** [ScrapeWithYuri/Live-Sports-Arbitrage-Bet-Finder#3]
I've installed all the necessary libraries and have been getting this error about the driver. Any idea how to resolve this?

<img width="1440" alt="Screen Shot 2022-12-20 at 12 38 55 AM" src="https://user-images.githubusercontent.com/117457257/208592114-0b81ded8-2816-42a2-9074-26a36500ac4d.png">

**Comment by personal-coding** [comment]
That error may be caused by having the wrong undetected chromedriver library, which may be causing the driver to not be loaded. Can you confirm that you've installed undetected-chromedriver-modified?

**Comment by caderob** [comment]
When I run with both undetected-chromedriver-modified & undetected-chromedriver installed, I get this error

<img width="1440" alt="Screen Shot 2022-12-20 at 3 08 17 PM" src="https://user-images.githubusercontent.com/117457257/208757822-bec6f925-d405-46e0-a6cc-a03
<img width="1440" alt="Screen Shot 2022-12-20 at 3 12 36 PM" src="https://user-images.githubusercontent.com/117457257/208757848-b156990c-0154-43bb-aafa-c7842bf0bcbc.png">
17689a2a0.png">

When I run with just the undetected-chromedriver-modified installed, I get this error

<img width="1440" alt="Screen Shot 2022-12-20 at 3 06 52 PM" src="https://user-images.githubusercontent.com/117457257/208757968-42c403d2-2332-4fdd-9f75-76ac
<img width="1440" alt="Screen Shot 2022-12-20 at 3 09 46 PM" src="https://user-images.githubusercontent.com/117457257/208757979-2c7df4a5-739a-4d09-96dc-8db3342b2671.png">
a8181201.png">

**Comment by caderob** [comment]
When I run with both **undetected-chromedriver-modified** & **undetected-chromedriver** dependencies installed, this is the error

<img width="1440" alt="Screen Shot 2022-12-20 at 3 08 17 PM" src="https://user-images.githubusercontent.com/117457257/208758226-99dfa4d2-54f5-47de-b737-1fb2f9c9c354.png">

<img width="1440" alt="Screen Shot 2022-12-20 at 3 12 36 PM" src="https://user-images.githubusercontent.com/117457257/208758260-802fec8e-f9ed-4f00-afff-3eb212845b3f.png">

**Comment by caderob** [comment]
When I run with just **undetected-chromedriver-modified** as a dependency installed, this is the error

<img width="1440" alt="Screen Shot 2022-12-20 at 3 06 52 PM" src="https://user-images.githubusercontent.com/117457257/208758461-229b6310-d87b-4190-9480-3a70a79fe83f.png">

<img width="1440" alt="Screen Shot 2022-12-20 at 3 09 46 PM" src="https://user-images.githubusercontent.com/117457257/208758487-f7e2bc89-c7df-411d-b9f2-8c3bf06ea9fd.png">

**Comment by personal-coding** [comment]
I think you may running into a conflict with having both `undetected-chromedriver` and `undetected-chromedriver-modified`. Can you delete undetected-chromedriver and try again? And try updating `import undetected_chromedriver.v2 as uc` to `import undetected_chromedriver as uc`

**Comment by caderob** [comment]
`undetected-chromedriver` has been deleted. `undetected-chromedriver-modified` is still active. Also updated `import undetected_chromedriver.v2 as uc` to `import undetected_chromedriver as uc`.

Same error as before occurs.

<img width="1440" alt="Screen Shot 2022-12-20 at 3 54 37 PM" src="https://user-images.githubusercontent.com/117457257/208764946-6e36897e-9c3c-4ba3-81b1-ffec5162e894.png">

**Comment by personal-coding** [comment]
1. If you use the `undetected-chromedriver` library, use `import undetected_chromedriver as uc` in the code
2. If you use the `undetected-chromedriver-modified` library, use `import undetected_chromedriver.v2 as uc` in the code

But, avoid having both libraries installed. You may be safest to just use the `undetected-chromedriver` library
