### ISSUE TITLE
Both files F and D using draftkings url

### ISSUE THREAD

**Issue by kick707** [ScrapeWithYuri/Live-Sports-Arbitrage-Bet-Finder#4]
F & D file using draftkings url /that's ok/
F & W file also using draftkings url /shud b William Hill's one.../

**Comment by personal-coding** [comment]
The [F & W - Arb_Website - Two Person.py](https://github.com/ScrapeWithYuri/Live-Sports-Arbitrage-Bet-Finder/blob/main/F%20%26%20W%20-%20Arb_Website%20-%20Two%20Person.py) file is accurate, but the `F & W - Arb_Website.py` was inadvertently copied over by the `F & D - Arb_Website.py` file while making formatting updates and adding comments. I've deleted the `F & W - Arb_Website.py` file, as I no longer have access to the original code (on an old computer).

That being said, the [F & D - Arb_Website.py](https://github.com/ScrapeWithYuri/Live-Sports-Arbitrage-Bet-Finder/blob/main/F%20%26%20D%20-%20Arb_Website.py) file is a template that could be expanded to William Hill by updating the XPath selectors.
