### ISSUE TITLE
Requirement Dependencies

### ISSUE THREAD

**Issue by edshaw42** [ScrapeWithYuri/Live-Sports-Arbitrage-Bet-Finder#7]
Is there an easy way to list a step by step on cloning and installing all dependencies?

**Comment by edshaw42** [comment]
I have it running, but it opens two instances of chrome (draftkings) and (fanduel), but I can never login to both. It seems like geolocate only allowed on one at a time, have you experienced this?

**Comment by personal-coding** [comment]
@edshaw42 During my tests, I was able to complete geolocation on both browsers. One of the two websites requires a program be downloaded to complete the geolocation, while the other completes geolocation in the browser. Is that potentially causing the issue?

**Comment by edshaw42** [comment]
@ScrapeWithYuri - figured out that issue, it was the url in the script is prefixed with "IL" for Illinois, once I changed that to my state, I got it to geolocate.. 

I did run into an issue, I uncommented your code to let it submit the bets itself and I got errors when it would try. 

I can try to set this up again tonight and let you know what the errors look like.

Great job on this!

**Comment by BeeRabbits** [comment]
This is truly Brilliant, this is very well done.

**Comment by edshaw42** [comment]
@Chealol  does it submit wagers for you?

**Comment by personal-coding** [comment]
@edshaw42 The IL prefix has now been removed in the code. Also, the submit button codes have been updated slightly. However, your error may be due to the HTML code having been updated since the code was written, which would require that the XPath selectors be updated.

**Comment by edshaw42** [comment]
@ScrapeWithYuri awesome, great job. I will give it another shot tonight!

**Comment by BeeRabbits** [comment]
@edshaw42 It does not but, I basically manually do it when it pops up as quick as possible lol. Still a wonderful job on this @ScrapeWithYuri

**Comment by edshaw42** [comment]
Agreed, such an awesome project.

**Comment by BeeRabbits** [comment]
There was one thing, I couldn't figure out this ModuleNotFoundError: No module named 'undetected_chromedriver.v2' except removing the .v2 then it all works, i am using python 3.10 as well. @ScrapeWithYuri

**Comment by edshaw42** [comment]
Yes. Same. Forgot I did that.

**Comment by personal-coding** [comment]
@Chealol that error occurs likely after downloading the undetected-chromedriver vs. undetected-chromedriver-modified library. The code uses the undetected-chromedriver-modified library, as the distinction was relevant at one point. However, the undetected-chromedriver library is sufficient now, so the .v2 is no longer necessary. I'll update.

**Comment by BeeRabbits** [comment]
@ScrapeWithYuri Ah, I see I figured it was something like that. Thank you!
