### ISSUE TITLE
Bot won't input bets

### ISSUE THREAD

**Issue by rolocyenom** [ScrapeWithYuri/Live-Sports-Arbitrage-Bet-Finder#8]
This is probably user error. But after uncommenting the code from the readme, the bot still doesn't actually input anything. Just puts them into my slip and then removes them after about 5-10 seconds.

**Comment by personal-coding** [comment]
@rolocyenom Does the program throw an error before removing the bets? It may be that the website's HTML changed, requiring the XPaths to be updated in the code

**Comment by rolocyenom** [comment]
I don't remember seeing any. It just wasn't inputting any amount for the bet or trying to submit any. I will check again tonight to verify it wasn't giving an error.

**Comment by rolocyenom** [comment]
@ScrapeWithYuri I'm receiving this error on startup. Opens both sites and then gives me this error. I'm using the F & D - Arb_Website.py.


`Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href,'/live')]//span[text()='Baseball']"}
  (Session info: chrome=112.0.5615.87)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0109DCE3+50899]
        (No symbol) [0x0102E111]
        (No symbol) [0x00F35588]
        (No symbol) [0x00F608F9]
        (No symbol) [0x00F60AFB]
        (No symbol) [0x00F8F902]
        (No symbol) [0x00F7B944]
        (No symbol) [0x00F8E01C]
        (No symbol) [0x00F7B6F6]
        (No symbol) [0x00F57708]
        (No symbol) [0x00F5886D]
        GetHandleVerifier [0x01303EAE+2566302]
        GetHandleVerifier [0x013392B1+2784417]
        GetHandleVerifier [0x0133327C+2759788]
        GetHandleVerifier [0x01135740+672048]
        (No symbol) [0x01038872]
        (No symbol) [0x010341C8]
        (No symbol) [0x010342AB]
        (No symbol) [0x010271B7]
        BaseThreadInitThunk [0x774B7D49+25]
        RtlInitializeExceptionChain [0x7789B74B+107]
        RtlClearBits [0x7789B6CF+191]`

**Comment by personal-coding** [comment]
@rolocyenom This error won't prevent the code from running. You can manually select the sport, then the code will proceed. The HTML code related to the sports selection likely changed since I wrote the program, requiring the XPath selector to be updated.

**Comment by Aferrara3** [comment]
@rolocyenom, I was just messing around with setting this up and can confirm that the XPath selector is no longer accurate for FanDuel - even from the top level "sportsbook-event-accordion__wrapper". Did you ever update all of the relevant selectors? If not I will probably take a swing at it tonight or tomorrow and can share.

**Comment by rolocyenom** [comment]
Hey guys,

Sorry for the delayed response. Work took over for a bit there and I had to push the hobbies aside. This explanation does make sense. I might be able to do some poking around this weekend.
